config/routes.rb
Rails.application.routes.draw do

  get 'comments/new'

  get 'topics/new'

  get 'sessions/new'

  resources 'users'
  resources 'topics'
  resources 'comments'

  get 'pages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/favorites', to: 'favorites#create'
  get '/favorites', to: 'favorites#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_text, presence: true



  belongs_to :topic
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :favorites
  has_many :comments
  # mount_uploader :image, ImageUploader
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true

  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: :topic
  has_many :comments
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])

  end

  def logged_in?
    !current_user.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    # debugger
    
    @comment = Comment.new

  end


  def create
    # debugger
    # @topic = Topic.find_by(id: params[:id])
    @topic = Topic.find_by(id: params[:topic_id])
    # debugger
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    # @comment.topic_id = @topic.id

    # debugger  user_id: current_user.id, , topic_id: params[:topic_id]
    if @comment.save

      redirect_to topics_path

    else
      # debugger
      render :new
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:comment_text, :topic_id)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    debugger
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    if favorite.save
      redirect_to topics_path, notice: 'お気に入りに登録しました'
    else
      redirect_to topics_path, notice: 'お気に入り登録に失敗しました'
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to root_path, alert: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end


  def destroy
    log_out
    redirect_to root_path
  end



  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    @topic = Topic.new
  end


  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path, notice: '投稿に成功しました'
    else
      flash.now[:alert] = "投稿に失敗しました"
    end
  end

  def index
    @topics = Topic.all
    # debugger
  end

  def edit
    # debugger
    @topic = Topic.find_by(id: params[:id])
  end

  def update
    @topic = Topic.find_by(id: params[:id])
    # debugger
    if @topic.update(topic_params)   #= current_user.topics.update(topic_params)
      redirect_to topics_path, notice: '編集を完了しました。'
    else
      render :edit
    end
  end


  def destroy
    @topic = Topic.find_by(id: params[:id])
    if @topic.delete
    redirect_to topics_path
    else
    render topics_path

    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: '登録が完了しました'
    else
      flash.now[:alert] = '登録に失敗しました'
      render :new
    end
  end


    private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @comment, url: comments_path do |f| %>
          <div class="form-group">
            <%= f.label :comment_text %>
            <%= f.text_area :comment_text, class: 'form-control' %>
            <%= f.hidden_field :topic_id, :value=>params[:topic_id] %>

          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterKari</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
        <div class="container">
          <%= link_to root_path do %>
            <span><%= image_tag 'icons/logo.png', class: 'navbar-brand' %></span>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li>
                <%= link_to '#' do %>
                  <%= image_tag 'icons/heart.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to '#' do %>
                  <%= image_tag 'icons/camera.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to logout_path, method: :delete do %>
                  <%= image_tag 'icons/logout.png' %>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to new_user_path do %>
                  <%= image_tag 'icons/register.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to login_path do %>
                  <%= image_tag 'icons/login.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to new_topic_path do %>
                  <%= image_tag 'icons/camera.png' %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign in', '#', class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', '#',class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>


小規模改修

app/views/topics/edit.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
        <%= image_tag @topic.image.url %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              User name: <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
              <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
            <% end %>
            <%= link_to new_comment_path(topic_id: topic.id), method: :get do %>

            <!-- topic_id: topic.id -->
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            <p class="topic-text">
            <%= topic.description %><br>

            <h3>コメント</h3>
            <% topic.comments.each do |comment| %>
              <p><%= comment.comment_text %></p>
            <% end %>

            <%= link_to "Edit", edit_topic_path(topic) %><br>
            <%= link_to "Delete", topic_path(topic), method: :delete %>

            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', '#',class: 'text-white' %>
      </div>
    </div>
  </div>
</div>